package mypackage;
// Generated 2019/8/4 �W�� 10:14:40 by Hibernate Tools 4.3.1



/**
 * NamePassword generated by hbm2java
 */
public class NamePassword  implements java.io.Serializable {


     private String name;
     private String password;

    public NamePassword() {
    }

    public NamePassword(String name, String password) {
       this.name = name;
       this.password = password;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "NamePassword{" + "name=" + name + ", password=" + password + '}';
    }




}


